on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - abcl-bin
          - ccl-bin

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v6
      - uses: 40ants/setup-lisp@v4
        with:
          asdf-system: cl-nbt/tests
      - run: |
          qlot exec ros run -- --eval '(progn (ql:quickloaf :rove) (uiop:quit (if (rove:run "cl-nbt/tests") 0 1)))'