on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - abcl-bin
          - ccl-bin

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v7
      - uses: 40ants/setup-lisp@v4
        with:
          asdf-system: cl-nbt/tests
      - run: |
          rm -rf ~/.cache/common-lisp/
          qlot exec ros run -- \
            --eval '(ql:quickload :cl-nbt/tests)' \
            --eval '(let ((result (rove:run :cl-nbt/tests))) (uiop:quit (if result 0 1)))'